name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  jekyll-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './'  # 告诉 GitHub 直接编译根目录下的 Jekyll 内容
      - name: Deploy
        uses: actions/deploy-pages@v4
